// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxx_dJGA82yAthSj1nyQm6N66zTSv3gNY',
    appId: '1:675569941563:web:0d373d71ecbf66d801301e',
    messagingSenderId: '675569941563',
    projectId: 'safqa-b3f7c',
    authDomain: 'safqa-b3f7c.firebaseapp.com',
    storageBucket: 'safqa-b3f7c.firebasestorage.app',
    measurementId: 'G-12QE274FWJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwYAd2cYGxxeWZwiIU3Jprkl72ey-wizI',
    appId: '1:675569941563:android:5faffc89537e02c001301e',
    messagingSenderId: '675569941563',
    projectId: 'safqa-b3f7c',
    storageBucket: 'safqa-b3f7c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBh9egMimzKOMBfszcSf-bW2K0gECrcr10',
    appId: '1:675569941563:ios:f2b58b6ed339f75501301e',
    messagingSenderId: '675569941563',
    projectId: 'safqa-b3f7c',
    storageBucket: 'safqa-b3f7c.firebasestorage.app',
    iosBundleId: 'com.example.safqaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBh9egMimzKOMBfszcSf-bW2K0gECrcr10',
    appId: '1:675569941563:ios:f2b58b6ed339f75501301e',
    messagingSenderId: '675569941563',
    projectId: 'safqa-b3f7c',
    storageBucket: 'safqa-b3f7c.firebasestorage.app',
    iosBundleId: 'com.example.safqaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxx_dJGA82yAthSj1nyQm6N66zTSv3gNY',
    appId: '1:675569941563:web:e7df3e94119d1bce01301e',
    messagingSenderId: '675569941563',
    projectId: 'safqa-b3f7c',
    authDomain: 'safqa-b3f7c.firebaseapp.com',
    storageBucket: 'safqa-b3f7c.firebasestorage.app',
    measurementId: 'G-388E0BNZVF',
  );
}
